services:
  demo-odoo:
    image: odoo:17.0@sha256:4959237918da385a5befe007fc95177bc2244c048ebc55097b7aa71c703e70ba
    container_name: demo-odoo
    hostname: demo-odoo
    depends_on:
      - demo-postgres
    environment:
      HOST: demo-postgres
    ports:
      - "8069:8069"
    networks:
      - demo-network
    volumes:
      - demo-odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons-customize:/mnt/extra-addons

  demo-postgres:
    image: postgres:16@sha256:71e27bf60b70bded003791b5573f8b808365613f341df20ffcf0c1ed7bc13ddf
    container_name: demo-postgres
    hostname: demo-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5438:5432"
    networks:
      - demo-network
    volumes:
      - demo-postgres-data:/var/lib/postgresql/data

volumes:
  demo-odoo-data:
    name: "demo-odoo-data"
  demo-postgres-data:
    name: "demo-postgres-data"

networks:
  demo-network:
    name: demo-network
    driver: bridge
