services:
  demo-odoo:
    image: odoo:19.0
    container_name: demo-odoo
    hostname: demo-odoo
    depends_on:
      - demo-postgres
    environment:
      HOST: demo-postgres
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    ports:
      - "80:8069"
    networks:
      - demo-network
    volumes:
      - demo-odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons-customize:/mnt/extra-addons

  demo-postgres:
    image: postgres:16-bookworm
    container_name: demo-postgres
    hostname: demo-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    networks:
      - demo-network
    volumes:
      - demo-postgres-data:/var/lib/postgresql/data

volumes:
  demo-odoo-data:
    name: "demo-odoo-data"
  demo-postgres-data:
    name: "demo-postgres-data"

networks:
  demo-network:
    name: demo-network
    driver: bridge
